configured_endpoints: 152
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/citibank-demo-business-inc-diplomat-bit%2Fgarbage-18eac09dbbd8688f13cdf64752aede763b50a60ffbb8ce1cf5238fda805d89d1.yml
openapi_spec_hash: 7ac6751bf85c0e2983c3bcda639e9953
config_hash: 214a3c49c09c931b0fac05109e397c3a
