configured_endpoints: 70
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/citibank-demo-business-inc-diplomat-bit%2Fjocall3-a822f8eb3bd0029a5ffa38a32d85c4eea2f98f8fb0b7d4889cee4f3002ae9d0d.yml
openapi_spec_hash: 55d7f1dac2bfa3c1bee4c2b89d5c78f1
config_hash: 41c883add8aeb22ea97ee35aa3753d45
